const BASE = "/assets";

export const RECIPE_IMAGES = {
  "add-user":                    `${BASE}/add-user.webp`,
  "air-fryer":                   `${BASE}/air-fryer.webp`,
  "back-icon":                   `${BASE}/back-icon.webp`,
  blender:                       `${BASE}/blender.webp`,
  "chef-mascot":                 `${BASE}/chef-mascot.webp`,
  "citrus-juicer":               `${BASE}/citrus-juicer.webp`,
  "coffe-machine":               `${BASE}/coffe-machine.webp`,
  "cook-bg-brown":               `${BASE}/cook-bg-brown.webp`,
  "cook-bg-green":               `${BASE}/cook-bg-green.webp`,
  "cook-bg-yellow":              `${BASE}/cook-bg-yellow.webp`,
  "cook-complete-alert":         `${BASE}/cook-complete-alert.webp`,
  "cook-peu-image":              `${BASE}/cook-peu-image.webp`,
  "cook-potato-wink":            `${BASE}/cook-potato-wink.webp`,
  cooked:                        `${BASE}/cooked.webp`,
  "exit-icon":                   `${BASE}/exit-icon.webp`,
  "food-steamer":                `${BASE}/food-steamer.webp`,
  house:                         `${BASE}/house.webp`,
  "left-arrow":                  `${BASE}/left-arrow.webp`,
  "level-icon":                  `${BASE}/level-icon.webp`,
  "login-naver":                 `${BASE}/login-naver.webp`,
  "main-bg":                     `${BASE}/main-bg.webp`,
  "main-character":              `${BASE}/main-character.webp`,
  "main-next":                   `${BASE}/main-next.webp`,
  "main-profile":                `${BASE}/main-profile.webp`,
  "main-weather":                `${BASE}/main-weather.webp`,
  "my-recipe-board":             `${BASE}/my-recipe-board.webp`,
  "my-recipe-borderline-beige":  `${BASE}/my-recipe-borderline-beige.webp`,
  "my-recipe-clip-beige":        `${BASE}/my-recipe-clip-beige.webp`,
  "my-recipe-clip-orange":       `${BASE}/my-recipe-clip-orange.webp`,
  "my-recipe-close":             `${BASE}/my-recipe-close.webp`,
  "my-recipe-level":             `${BASE}/my-recipe-level.webp`,
  "my-recipe-time":              `${BASE}/my-recipe-time.webp`,
  "nav-chat-click":              `${BASE}/nav-chat-click.webp`,
  "nav-chat-non":                `${BASE}/nav-chat-non.webp`,
  "nav-cook-click":              `${BASE}/nav-cook-click.webp`,
  "nav-cook-non":                `${BASE}/nav-cook-non.webp`,
  "nav-home-click":              `${BASE}/nav-home-click.webp`,
  "nav-home-non":                `${BASE}/nav-home-non.webp`,
  "nav-my-click":                `${BASE}/nav-my-click.webp`,
  "nav-my-non":                  `${BASE}/nav-my-non.webp`,
  oven:                          `${BASE}/oven.webp`,
  "potato-face":                 `${BASE}/potato-face.webp`,
  potato_face:                   `${BASE}/potato_face.webp`,
  "rice-cooker":                 `${BASE}/rice-cooker.webp`,
  "splash-bg":                   `${BASE}/splash-bg.webp`,
  "splash-potato":               `${BASE}/splash-potato.webp`,
  "stovetop-waffle":             `${BASE}/stovetop-waffle.webp`,
  "time-icon":                   `${BASE}/time-icon.webp`,
  "toast-appliance":             `${BASE}/toast-appliance.webp`,
  "birthday-main-character_v2":  `${BASE}/birthday-main-character_v2.webp`,
  cloud:                         `${BASE}/cloud.webp`,
  rain:                          `${BASE}/rain.webp`,
  snow:                          `${BASE}/snow.webp`,
  storm:                         `${BASE}/storm.webp`,
  sun:                           `${BASE}/sun.webp`,
  wind:                          `${BASE}/wind.webp`,

  // public/ 에 이미 존재하는 파일들은 직접 참조
  "loading-motion":    "/loading-motion.gif",
  "loading-bg-phone":  "/loading-bg-phone.png",

  // 레시피 이미지 없을 때 기본 대체 이미지 (public/ 에 존재)
  default_img:         "/peu_wink.png",
};
