// 모든 이미지는 frontend/public/ 에 위치 (로컬 파일)
export const RECIPE_IMAGES = {
  // 실제 존재하는 파일 (.png)
  "add-user":                    "/add-user.png",
  "air-fryer":                   "/air-fryer.png",
  "birthday-main-character":     "/birthday-main-character.png",
  "birthday-main-character_v2":  "/birthday-main-character_v2.png",
  blender:                       "/blender.png",
  "chef-mascot":                 "/chef-mascot.png",
  "citrus-juicer":               "/citrus-juicer.png",
  "coffe-machine":               "/coffe-machine.png",
  "cook-bg-brown":               "/cook-bg-brown.png",
  "cook-bg-yellow":              "/cook-bg-yellow.png",
  "cook-complete-alert":         "/cook-complete-alert.png",
  "cook-potato-wink":            "/cook-potato-wink.png",
  cooked:                        "/cooked.png",
  "exit-icon":                   "/exit-icon.png",
  "food-steamer":                "/food-steamer.png",
  house:                         "/house.png",
  "left-arrow":                  "/left-arrow.png",
  "level-icon":                  "/level-icon.png",
  "login-naver":                 "/login-naver.png",
  "main-bg":                     "/main-bg.png",
  "main-character":              "/main-character.png",
  "main-next":                   "/main-next.png",
  "main-profile":                "/main-profile.png",
  "main-weather":                "/main-weather.png",
  "my-recipe-board":             "/my-recipe-board.png",
  "my-recipe-borderline-beige":  "/my-recipe-borderline-beige.png",
  "my-recipe-clip-beige":        "/my-recipe-clip-beige.png",
  "my-recipe-clip-orange":       "/my-recipe-clip-orange.png",
  "my-recipe-close":             "/my-recipe-close.png",
  "my-recipe-level":             "/my-recipe-level.png",
  "my-recipe-time":              "/my-recipe-time.png",
  "nav-chat-click":              "/nav-chat-click.png",
  "nav-chat-non":                "/nav-chat-non.png",
  "nav-cook-click":              "/nav-cook-click.png",
  "nav-cook-non":                "/nav-cook-non.png",
  "nav-home-non":                "/nav-home-non.png",
  "nav-my-click":                "/nav-my-click.png",
  "nav-my-non":                  "/nav-my-non.png",
  oven:                          "/oven.png",
  "peu_banjuk":                  "/peu_banjuk.png",
  "peu_chicken":                 "/peu_chicken.png",
  "peu_cook":                    "/peu_cook.png",
  "peu_gimbab":                  "/peu_gimbab.png",
  "peu_hurai":                   "/peu_hurai.png",
  "peu_icecream":                "/peu_icecream.png",
  "peu_pizza":                   "/peu_pizza.png",
  "peu_ramen":                   "/peu_ramen.png",
  "peu_salad":                   "/peu_salad.png",
  "peu_wink":                    "/peu_wink.png",
  "potato-face":                 "/potato-face.png",
  potato_face:                   "/potato-face.png",
  "rice-cooker":                 "/rice-cooker.png",
  "splash-bg":                   "/splash-bg.png",
  "splash-potato":               "/splash-potato.png",
  "stovetop-waffle":             "/stovetop-waffle.png",
  "time-icon":                   "/time-icon.png",
  "toast-appliance":             "/toast-appliance.png",

  // 날씨 아이콘 (이제 실제 파일 있음)
  cloud: "/cloud.png",
  rain:  "/rain.png",
  snow:  "/snow.png",
  storm: "/storm.png",
  sun:   "/sun.png",
  wind:  "/wind.png",

  // 실제 파일 없는 키 → 유사한 파일로 대체
  "back-icon":    "/left-arrow.png",      // back-icon.png 없음
  "cook-bg-green": "/cook-bg-green.png",
  "cook-peu-image": "/peu_cook.png",      // cook-peu-image.png 없음
  "nav-home-click": "/nav-home-non.png",  // nav-home-click.png 없음

  // 로딩
  "loading-motion":   "/loading-motion.gif",
  "loading-bg-phone": "/loading-bg-phone.png",

  // 레시피 기본 이미지
  default_img: "/default-food.jpg",
};
